export const SIGNUP_API_REQUEST = "SIGNUP_API_REQUEST";
export const SIGNUP_SUCCESS_RESPONSE = "SIGNUP_SUCCESS_RESPONSE";
export const SIGNUP_FAILURE_RESPONSE = "SIGNUP_FAILURE_RESPONSE";

export const VERIFY_OTP_API_REQUEST = "VERIFY_OTP_API_REQUEST";
export const VERIFY_OTP_SUCCESS_RESPONSE = "VERIFY_OTP_SUCCESS_RESPONSE";
export const VERIFY_OTP_FAILURE_RESPONSE = "VERIFY_OTP_FAILURE_RESPONSE";

export const SEND_OTP_API_REQUEST = "SEND_OTP_API_REQUEST";
export const SEND_OTP_SUCCESS_RESPONSE = "SEND_OTP_SUCCESS_RESPONSE";
export const SEND_OTP_FAILURE_RESPONSE = "SEND_OTP_FAILURE_RESPONSE";

export const RESEND_OTP_API_REQUEST = "RESEND_OTP_API_REQUEST";
export const RESEND_OTP_SUCCESS_RESPONSE = "RESEND_OTP_SUCCESS_RESPONSE";
export const RESEND_OTP_FAILURE_RESPONSE = "RESEND_OTP_FAILURE_RESPONSE";

export const UPDATE_PASSWORD_API_REQUEST = "UPDATE_PASSWORD_API_REQUEST";
export const UPDATE_PASSWORD_SUCCESS_RESPONSE =
  "UPDATE_PASSWORD_SUCCESS_RESPONSE";
export const UPDATE_PASSWORD_FAILURE_RESPONSE =
  "UPDATE_PASSWORD_FAILURE_RESPONSE";

export const LOGIN_USER = "LOGIN_USER";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const REMOVE_CURRENT_USER = "REMOVE_CURRENT_USER";
export const ERROR_SET_USER = "ERROR_SET_USER";

export const CREATE_TODO_API_REQUEST = "CREATE_TODO_API_REQUEST";
export const CREATE_TODO_SUCCESS_RESPONSE = "CREATE_TODO_SUCCESS_RESPONSE";
export const CREATE_TODO_FAILURE_RESPONSE = "CREATE_TODO_FAILURE_RESPONSE";

export const UPDATE_TODO_API_REQUEST = "UPDATE_TODO_API_REQUEST";
export const UPDATE_TODO_SUCCESS_RESPONSE = "UPDATE_TODO_SUCCESS_RESPONSE";
export const UPDATE_TODO_FAILURE_RESPONSE = "UPDATE_TODO_FAILURE_RESPONSE";


export const DELETE_TODO_API_REQUEST = "DELETE_TODO_API_REQUEST";
export const DELETE_TODO_SUCCESS_RESPONSE = "DELETE_TODO_SUCCESS_RESPONSE";
export const DELETE_TODO_FAILURE_RESPONSE = "DELETE_TODO_FAILURE_RESPONSE";

export const FETCH_ALL_TODO_API_REQUEST = "FETCH_ALL_TODO_API_REQUEST";
export const FETCH_ALL_TODO_SUCCESS_RESPONSE =
  "FETCH_ALL_TODO_SUCCESS_RESPONSE";
export const FETCH_ALL_TODO_FAILURE_RESPONSE =
  "FETCH_ALL_TODO_SUCCESS_RESPONSE";

export const FETCH_ALL_TODOS_API_REQUEST = "FETCH_ALL_TODO_API_REQUEST";
export const FETCH_ALL_TODOS_SUCCESS_RESPONSE =
  "FETCH_ALL_TODO_SUCCESS_RESPONSE";
export const FETCH_ALL_TODOS_FAILURE_RESPONSE =
  "FETCH_ALL_TODO_SUCCESS_RESPONSE";
